image: ghcr.io/astral-sh/uv:latest

test:
  stage: test
  script:
  - uv sync --locked --dev
  - sphinx-build -b html .docs public
  only:
  - develop
  except:
  - master
  artifacts:
    paths:
    - public

# pages:
#   stage: deploy
#   script:
#   - pip install -U sphinx
#   - sphinx-build -b html . public
#   artifacts:
#     paths:
#     - public
#   only:
#   - master